language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: 
# use pyaml for tests above py26
 - pip install -r requirements.txt
 - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then pip install pyaml; fi
 - "python setup.py install"
# command to run tests
script: python test.py
